import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="absolute inset-0 bg-cover"
        style={{
          backgroundImage: "url('/haj.jpg')",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <div className="relative max-w-[1000px] mx-auto w-[100vw]">
          {/* Yarim shaffof fon qatlami qo'shish */}
          <div className="absolute inset-0 bg-black opacity-40 z-0"></div>

          {/* Asosiy kontent */}
          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
